### ISSUE TITLE
Unable to launch commuter

### ISSUE THREAD

**Issue by aquazure** [nteract/commuter#249] opened 2019-01-21 08:12 UTC
I am trying to set up commuter to work with an s3 storage backend on an Amazon EC2 instance.

Referencing the documentation at [https://github.com/nteract/commuter](https://github.com/nteract/commuter) I have set the relevant environment variables with the following commands:
```
export COMMUTER_STORAGE_BACKEND=s3
export COMMUTER_BUCKET=bucket-name
```
But when trying to launch commuter via `commuter` command I get the following error:
```
CONFIGURED DISCOVERY none
Running in the current working directory,  /home/jupyter-tljh_admin
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './config/babel.flow.config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@nteract/webpack-configurator/index.js:12:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
Would love to get this set up, is this a reasonable place to ask for this sort of help?
Thanks,

**Comment by erolosty** [comment] 2019-01-22 18:45
@aquazure yours may be a dupe of: https://github.com/nteract/commuter/issues/247

**Comment by aquazure** [comment] 2019-01-23 13:58
@erolosty 

Retried with:
```
npm install https://github.com/nteract/commuter.git
yarn add https://github.com/nteract/commuter.git
```
As well as cloning master branch into local directory and running `commuter ` command

I still get thrown the same error, however...

**Comment by rgbkrk** [comment] 2019-01-23 20:07
Super sorry! This is the right repo. We've been going through some structural changes with the nteract repos so I didn't get this one back to a normal state. On my end I've been focused on an internal fork of commuter (at Netflix) and want to get the changes to be minimal on both while getting prod mode back to working for the deployed version.

I've sadly not been running with the `commuter` command, instead using either `yarn dev` or `yarn start` (after assets have been built). Does that work for you on `master` for the moment?

**Comment by erolosty** [comment] 2019-01-23 21:20
Hey, don't worry! We all have day jobs, that tend to not focus around supporting random folk from the interwebs :)

I managed to get it to start with:

`npm run start`

This gets me into a state in which the bottom half of each page (directory tree and notebooks) takes a full screen's worth of space and simply says:

An unexpected error has occurred.

in the center of the page. 

If there is some way to turn up the verbosity of logging, I'd be happy to try it out. My guess (given that this is the issue, that started me down the path to building it myself, when the version in npm broke) is that the cause of the error message is the same as: https://github.com/nteract/commuter/issues/248

But I don't have anything in the logs that proves it

**Comment by erolosty** [comment] 2019-02-07 22:15
ping /feelsbad

**Comment by romeran** [comment] 2019-02-10 15:07
Guess it's the same issue as [here](https://github.com/nteract/nteract/issues/3666)?
@rgbkrk any news?

**Comment by rgbkrk** [comment] 2019-02-10 17:53
I just migrated all the issues for commuter over to this repo and will start handling an overhaul of commuter with a few other folks. My most recent relevant update is from https://github.com/nteract/commuter/issues/249#issuecomment-456947550:

> Super sorry! This is the right repo. We've been going through some structural changes with the nteract repos so I didn't get this one back to a normal state. On my end I've been focused on an internal fork of commuter (at Netflix) and want to get the changes to be minimal on both while getting prod mode back to working for the deployed version externally.

> I've sadly not been running with the `commuter` command, instead using either `yarn dev` or `yarn start` (after assets have been built). Does that work for you on `master` for the moment?

**Comment by SelinGungor** [comment] 2019-02-25 15:13
Is this Issue fixed? I am getting the error below, after installing babel manually `npm install -g babel-cli`:

`SyntaxError: backend/config.js: Unexpected token, expected , (3:22)
  1 | // @flow
  2 |
> 3 | function deprecate(env: Object, oldVar: string, newVar: string) {
    |                       ^
  4 |   if (env[oldVar]) {
  5 |     console.warn(`${oldVar} is deprecated, please use ${newVar}`);
  6 |   }
`

**Comment by rgbkrk** [comment] 2019-02-25 17:54
It's not fixed and not ready for consumption currently. We're doing some internal fixups and will be posting a refreshed commuter soon.

Curiosity -- will you be backing notebooks with local storage or S3?

**Comment by taniki** [comment] 2019-02-26 14:04
I managed to run it with `pm2`. There is a weird react error but nothing critical. I am using it with s3 over s3fs because commuter doesn't seem to support s3 custom endpoint yet (same for papermill).

**Comment by SelinGungor** [comment] 2019-02-26 15:25
Local server @rgbkrk.

**Comment by erolosty** [comment] 2019-02-26 18:30
Local Storage

**Comment by weldpua2008** [comment] 2019-02-27 11:06
@taniki Can you share how you run it?

```
# export COMMUTER_STORAGE_BACKEND=s3
# export COMMUTER_BUCKET=bucket-name
# /usr/local/nodejs-binary-8.15.0/bin/pm2 start commuter
[PM2] Starting /usr/bin/commuter in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ commuter │ 0  │ N/A     │ fork │ 13273 │ online │ 0       │ 0s     │ 0%  │ 15.1 MB   │ root │ disabled │
└──────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
# /usr/local/nodejs-binary-8.15.0/bin/pm2 logs commuter 
/root/.pm2/logs/commuter-error.log last 15 lines:
0|commuter |     at Object.Module._extensions..js (module.js:664:10)
0|commuter |     at Module.load (module.js:566:32)
0|commuter |     at tryModuleLoad (module.js:506:12)
0|commuter |     at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' }
0|commuter | { Error: Cannot find module './config/babel.flow.config'
0|commuter |     at Function.Module._resolveFilename (module.js:548:15)
0|commuter |     at Function.Module._load (module.js:475:25)
0|commuter |     at Module.require (module.js:597:17)
0|commuter |     at require (internal/module.js:11:18)
0|commuter |     at Object.<anonymous> (/usr/lib/node_modules/@nteract/commuter/node_modules/@nteract/webpack-configurator/index.js:12:25)
0|commuter |     at Module._compile (module.js:653:30)
0|commuter |     at Object.Module._extensions..js (module.js:664:10)
0|commuter |     at Module.load (module.js:566:32)
0|commuter |     at tryModuleLoad (module.js:506:12)
0|commuter |     at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' }

```

**Comment by taniki** [comment] 2019-02-27 15:02
@weldpua2008 

ecosystem.config.js

```
module.exports = {
  apps : [{
    name: 'commuter',
    script: 'lib/index.js',

    instances: 1,
    autorestart: true,
    watch: true,
    max_memory_restart: '1G',
    env: {
      NODE_ENV: 'development'
    },
    env_production: {
      NODE_ENV: 'production',
      
      COMMUTER_STORAGE_BACKEND: 'local',
      COMMUTER_PORT: '80',
      COMMUTER_LOCAL_STORAGE_BASEDIRECTORY: "/root/notebooks/"
    }
  }]
};
```

and

```
$ pm2 [start/restart] ecosystem.config.js --env production
```

**Comment by weldpua2008** [comment] 2019-02-27 15:51
@taniki thank you for your quick response.

I tried the solution but it fails in same way:
```
0|commuter  | { Error: Cannot find module './config/babel.flow.config'
0|commuter  |     at Function.Module._resolveFilename (module.js:548:15)
0|commuter  |     at Function.Module._load (module.js:475:25)
0|commuter  |     at Module.require (module.js:597:17)
0|commuter  |     at require (internal/module.js:11:18)
0|commuter  |     at Object.<anonymous> (/usr/local/nodejs-binary-8.15.0/lib/node_modules/@nteract/commuter/node_modules/@nteract/webpack-configurator/index.js:12:25)
0|commuter  |     at Module._compile (module.js:653:30)
0|commuter  |     at Object.Module._extensions..js (module.js:664:10)
0|commuter  |     at Module.load (module.js:566:32)
0|commuter  |     at tryModuleLoad (module.js:506:12)
0|commuter  |     at Function.Module._load (module.js:498:3)
0|commuter  |     at Module.require (module.js:597:17)
0|commuter  |     at require (internal/module.js:11:18)
0|commuter  |     at Object.<anonymous> (/usr/local/nodejs-binary-8.15.0/lib/node_modules/@nteract/commuter/next.config.js:1:84)
0|commuter  |     at Module._compile (module.js:653:30)
0|commuter  |     at Object.Module._extensions..js (module.js:664:10)
0|commuter  |     at Module.load (module.js:566:32) code: 'MODULE_NOT_FOUND' }

```

**Comment by taniki** [comment] 2019-02-27 17:14
@weldpua2008 you should try with current `master` branch instead of npm package. That what I am doing.

**Comment by romeran** [comment] 2019-03-21 10:33
Hi @rgbkrk, any news?

**Comment by captainsafia** [comment] 2019-04-28 18:57
Hello folks!

I was able to reproduce this on my local machine in commuter v.5.7.0. I've publish a new minor version of commuter (5.8.0) that resolves this issue on my machine. Upgrading to this new minor version should resolve this issue.

**Closed by captainsafia** 2019-04-28 18:57 UTC
