### ISSUE TITLE
Error: Cannot find module './config/babel.flow.config'

### ISSUE THREAD

**Issue by KIRILLxBREAK** [nteract/commuter#256] opened 2019-04-01 19:20 UTC
I use a README way to install: `npm install @nteract/commuter -g`
Then, I try to start by `commuter` and get this error `Error: Cannot find module './config/babel.flow.config'`.

**Comment by captainsafia** [comment] 2019-04-28 18:38
Hello @KIRILLxBREAK and thanks for opening this issue.

This is a dupe of the existing issue https://github.com/nteract/commuter/issues/249 so I'll close this issue in favor of tracking everything on that one.

I'll see if I this is trivial to fix and I can knock it out in a patch release of commuter.

**Closed by captainsafia** 2019-04-28 18:38 UTC
