### ISSUE TITLE
TypeError: "r is undefined"

### ISSUE THREAD

**Issue by taniki** [nteract/commuter#254] opened 2019-03-06 11:20 UTC
I have this javascript error on the current master.

```
$ yarn
$ yarn build:all
$ ./bin.js
```

https://scope.11d.im

**Comment by captainsafia** [comment] 2019-05-03 02:02
Hello @taniki! Thanks for opening this issue.

I'm unable to reproduce this issue locally. Can you provide more information about your set up?

**Comment by taniki** [comment] 2019-05-03 09:14
I have tried on a local ubuntu computer with current lts of node and inside a docker container running `node:10` (e.g. https://github.com/etalab/autopsy/blob/master/commuter/Dockerfile).

I remember having the same the error using various ways to start the service but I might have missed the right one :)

**Comment by guzmud** [comment] 2019-07-01 12:28
Hi, I'm having a similar issue, so in case more info can be of use for debug :
- inside a Ubuntu 16.04.4 LTS container 
- using https://deb.nodesource.com/setup_12.x as a source for nodejs
- using https://dl.yarnpkg.com/debian/ stable main as a source for yarn
- installing both using apt then using yarn to install commuter
- running commuter through supervisor simply using "commuter" (linked to /usr/local/bin/commuter, a node script looking for "./lib/index.js")

**Comment by captainsafia** [comment] 2019-07-10 04:09
Thanks for posting the additional details!

I was able to track down roughly where the error is bubbling up from. It is bubbling up via our styled-jsx dependency in the `pages/view.js` file but I'm not sure what is causing it at the moment. Will take a look at this at some point when I have time.

If either of you are able to find any leads on what might be going on based on the breadcrumb above, feel free to submit a PR!

**Comment by guzmud** [comment] 2019-07-10 07:49
Glad I could help, though js ain't my thing so I just leave it here, sorry ! Gl Hf.

**Comment by taniki** [comment] 2019-07-10 21:58
Something is going wrong between the server side rendering and the brower rendering of `browse-header.js` and `header.js`. I am not acquainted to react and this is also seems to be related to previous version of next.

**Comment by taniki** [comment] 2019-07-11 00:11
Somehow I maked it work by upgrading the full stack with an `yarn upgrade --latest` and cleaning some legacy code while digging next 9 documentation. I don't know if it will be useful to propose a PR with a random migration from next 7 to last release.

**Comment by captainsafia** [comment] 2019-07-16 04:08
Closing now that @taniki's pull request has been merged. Thanks all!

**Closed** 2019-07-16 04:07 UTC
