### ISSUE TITLE
Development steps and failure on the installed version ? 

### ISSUE THREAD

**Issue by tkang007** [nteract/commuter#247] opened 2019-01-14 18:25 UTC
Hi There,

What is the correct steps for using commuter at the source build when do clone from url of the github, https://github.com/nteract/commuter.git,

Below step on the README file looks not up to date.
git clone git@github.com:nteract/nteract.git
cd nteract
yarn
yarn app:commuter
open http://localhost:4000

Could anybody update the file with correct steps?

When installed with, yarn global add @nteract/commuter

it was failed with below message:
CONFIGURED DISCOVERY none
module.js:550
    throw err;
    ^

Error: Cannot find module './config/babel.flow.config'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@nteract/webpack-configurator/index.js:12:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

What tag or branch do you recommend for jupyter notebook readonly static site ?

Thanks in advanced.

**Comment by captainsafia** [comment] 2019-04-28 18:39
Hello @tkang007 and thanks for opening this!

This is a dupe of https://github.com/nteract/commuter/issues/249 so I'll close this issue in favor of tracking the problem on that one.

**Closed by captainsafia** 2019-04-28 18:39 UTC
