### ISSUE TITLE
Demo URL Timeout / Project Error

### ISSUE THREAD

**Issue by robertdefilippi** [nteract/commuter#260] opened 2019-05-02 14:51 UTC
Hello,

When I try to view the demo (https://nteract-commuter-glitch-demo.glitch.me/view/) I either get a url timeout message or this,

```
failed to start application on nteract-commuter-glitch-demo.glitch.me

This is most likely because your project has a code error.
Check your project logs, fix the error and try again.
```

Is this something my browser is doing?

Thanks,

**Comment by captainsafia** [comment] 2019-05-03 01:27
Hello @robertdefilippi! Thanks for opening this issue.

I'm able to reproduce this issue. I've updated the version of commuter used in the demo but that doesn't seem to resolve it. I wonder if this might be an issue with Glitch itself.

@hydrosquall Any ideas?

**Comment by hydrosquall** [comment] 2019-05-03 19:44
I took a look at the code logs. To do this, I opened "console", and ran npm install, followed by `less` on the resulting installation error message, followed by

```bash
warn tar ENOSPC: no space left on device, write
... tens of lines about files not existing
```

I checked the Glitch docs to see what the restriction on project filesize is, since the 
https://glitch.com/help/restrictions/ lists the limit at 200 MB. The app root directory uses 180 MB, so Is suspect the app is running up against the limit. However, this limit shouldn't apply to the contents of node_modules.

@captainsafia , do you know if commuter copies any of the dependencies to outside node_modules after installation? I've dm'd the Glitch team to see if they might additional insight on why installing this 1 package uses up all the space on the host, or if perhaps the space limit has changed.

**Comment by hydrosquall** [comment] 2019-05-08 03:51
Hi @robertdefilippi ,

I spoke with glitch's support team via Twitter, and we rest a setting on the backend which ensures the project uses a shared folder for storing the project's NPM dependencies. The demo seems to work for me now. Let us know if it works for you too, if so we can close this issue.

**Comment by captainsafia** [comment] 2019-05-16 01:12
Thanks for taking the time to do this digging, @hydrosquall! I'll go ahead and close this issue now since I was able to load the demo.

@robertdefilippi If you are still running into the problem, feel free to re-open this issue.

**Closed by captainsafia** 2019-05-16 01:12 UTC
