### ISSUE TITLE
Commuter does not run on macOS

### ISSUE THREAD

**Issue by nikhilkuria** [nteract/commuter#250] opened 2018-11-14 09:15 UTC
I followed the instructions to install it 
`yarn global add @nteract/commuter` 

Afterwards, when i try to run it using 
`COMMUTER_LOCAL_STORAGE_BASEDIRECTORY=<~/dev/notebooks> commuter`

it fails with the following error
```
CONFIGURED DISCOVERY none
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module '../../babel.flow.config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/nkose/.config/yarn/global/node_modules/@nteract/webpack-configurator/index.js:12:25)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```

**Comment by captainsafia** [comment] 2019-04-28 18:58
Hello folks! I'm closing this issue as it is a duplicate of #249. Please read that thread for a resolution for this problem.

**Closed** 2019-04-29 02:51 UTC
